---
title: "A NOVEL METHOD FOR QUANTIFYING SAVANNA FIRE INTENSITY UNDER FIELD CONDITIONS: Appendix"
author: "Godwin, D.S. and Holdo, R.M"
output:
  html_document:
    keep_md: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
---

```{r, echo = FALSE, include = FALSE, results='hide'}

knitr::knit('Analysis.Rmd')

```
# Figures

## Figure 1

```{r, echo = FALSE, fig.height=11,fig.width=8.5, warning=FALSE}
b <- subset(iButtonMerge_calibration,Trial_Number != "Control")
a <- thermoMerge

a$Trial_Number <- as.numeric(as.character(a$Trial_Number))
b$Trial_Number <- as.numeric(as.character(b$Trial_Number))

b <- ddply(b,.(Trial_Number),mutate,Seconds = Time - min(Time))
a <- ddply(a,.(Trial_Number),mutate,Seconds = Time - min(Time))

a$Seconds <- as.numeric(a$Seconds)
b$Seconds <- as.numeric(b$Seconds)

a <- subset(a,!is.na(a$Trial_Number))
b <- subset(b,!is.na(b$Trial_Number))

toPlot <- ggplot(data = a, aes(x = Seconds, y = log(Temperature)))+
  myTheme+
  geom_line(color="black", size = 1)+
  geom_line(data = b,
            color="red",
            size = 1,
            aes(x = Seconds, y = log(Temperature)))+
  facet_wrap(~Trial_Number, nrow = 14, scales = "free")

toPlot

rm(a)
rm(b)

````

# Tables

## Table 1

Residual variance of Tmax ~ Biomass as explained by weather covariates

```{r echo=FALSE,results='asis'}
htmlreg(l=list(TCresids_by_RHmean,TCresids_by_WSmean,TCresids_by_WSmax,TCresids_by_RHmin), doctype = F, html.tag = TRUE, star.symbol="\\*", inline.css = TRUE, head.tag = FALSE, body.tag = FALSE, center = FALSE, single.row = TRUE, caption = "Residual Variance, Thermocouples", custom.model.names = c("Residuals ~ mean(Relative Humidity)","TC Residuals ~ mean(Wind Speed)","Residuals ~ max(Wind Speed)","Residuals ~ min(RH)"))
```

## Table 2

Residual variance of Imax ~ Biomass as explained by weather covariates

```{r echo=FALSE,results='asis'}


htmlreg(l=list(IBresids_by_RHmean,IBresids_by_WSmean,IBresids_by_WSmax,IBresids_by_RHmin), doctype = F, html.tag = TRUE, star.symbol="\\*", inline.css = TRUE, head.tag = FALSE, body.tag = FALSE, center = FALSE, single.row = TRUE, caption = "", custom.model.names = c("iButton Residuals ~ mean(Relative Humidity)","iButton Residuals ~ mean(Wind Speed)","iButton Residuals ~ max(Wind Speed)","iButton Residuals ~ min(RH)"))

```